# Generated by Django 5.0.7 on 2026-02-18 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estructura", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="user",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="tipo_usuario",
            field=models.CharField(
                choices=[
                    ("PROPIETARIO", "Propietario"),
                    ("INQUILINO", "Inquilino"),
                    ("PERSONAL", "Personal"),
                ],
                default="PROPIETARIO",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="vivienda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="estructura.vivienda",
            ),
        ),
    ]
