# Generated by Django 5.0.7 on 2026-03-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_role_user_activo_user_tipo_usuario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("STAFF", "Personal"),
                    ("USER", "Usuario"),
                ],
                default="USER",
                max_length=10,
            ),
        ),
    ]
