# Generated by Django 5.0.7 on 2026-02-18 20:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Urbanizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("direccion", models.CharField(max_length=255)),
                ("localidad", models.CharField(max_length=100)),
                ("provincia", models.CharField(max_length=100)),
                ("codigo_postal", models.CharField(max_length=10)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Urbanización",
                "verbose_name_plural": "Urbanizaciones",
            },
        ),
        migrations.CreateModel(
            name="Vivienda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referencia", models.CharField(max_length=100)),
                ("direccion_detalle", models.CharField(max_length=255)),
                ("propietario_nombre", models.CharField(max_length=200)),
                ("activa", models.BooleanField(default=True)),
                (
                    "urbanizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viviendas",
                        to="estructura.urbanizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vivienda",
                "verbose_name_plural": "Viviendas",
            },
        ),
        migrations.CreateModel(
            name="Invitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("usada", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_expiracion", models.DateTimeField()),
                (
                    "vivienda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitaciones",
                        to="estructura.vivienda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitación",
                "verbose_name_plural": "Invitaciones",
            },
        ),
    ]
