# Generated by Django 5.0.7 on 2026-03-12 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carrier",
                    models.CharField(
                        choices=[
                            ("AMAZON", "Amazon"),
                            ("CORREOS", "Correos"),
                            ("SEUR", "SEUR"),
                            ("DHL", "DHL"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("delivered", models.BooleanField(default=False)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
