"""
Django settings for issueflow project.

Generated by 'django-admin startproject' using Django 5.0.7.
"""

from pathlib import Path


# --------------------------------------------------
# RUTAS BASE DEL PROYECTO
# --------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# --------------------------------------------------
# SEGURIDAD (DESARROLLO)
# --------------------------------------------------
# ⚠️ En producción esta clave NUNCA debe ir aquí
SECRET_KEY = "django-insecure-vy!&v#22_gm9)9p#$)(4pp_87+nr#dw4&m&2xo=)dt9(pk^_7m"

DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]


# --------------------------------------------------
# APLICACIONES INSTALADAS
# --------------------------------------------------
INSTALLED_APPS = [
    # Apps de Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third party
    "rest_framework",
    "corsheaders",

    # Apps del proyecto
    "users",
    "incidents",
    "comments",
    "estructura",
    "reservations",
    "packages",
    "access",
    "works",
    "notifications",
    
]


# --------------------------------------------------
# MIDDLEWARE
# --------------------------------------------------
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # debe ir arriba

    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# --------------------------------------------------
# CONFIGURACIÓN DE URLs
# --------------------------------------------------
ROOT_URLCONF = "issueflow.urls"


# --------------------------------------------------
# PLANTILLAS
# --------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# --------------------------------------------------
# WSGI
# --------------------------------------------------
WSGI_APPLICATION = "issueflow.wsgi.application"


# --------------------------------------------------
# BASE DE DATOS
# --------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# --------------------------------------------------
# VALIDACIÓN DE CONTRASEÑAS
# --------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# --------------------------------------------------
# INTERNACIONALIZACIÓN
# --------------------------------------------------
LANGUAGE_CODE = "es-es"
TIME_ZONE = "Europe/Madrid"

USE_I18N = True
USE_TZ = True


# --------------------------------------------------
# ARCHIVOS ESTÁTICOS
# --------------------------------------------------
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]


# --------------------------------------------------
# USUARIO PERSONALIZADO
# --------------------------------------------------
AUTH_USER_MODEL = "users.User"


# --------------------------------------------------
# AUTENTICACIÓN
# --------------------------------------------------
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/incidents/"
LOGOUT_REDIRECT_URL = "/login/"


# --------------------------------------------------
# DJANGO REST FRAMEWORK
# --------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}


# --------------------------------------------------
# CORS (REACT + DJANGO)
# --------------------------------------------------
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

# 🔥 CLAVE PARA QUE FUNCIONEN LAS COOKIES ENTRE PUERTOS
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
]

SESSION_COOKIE_SAMESITE = None
CSRF_COOKIE_SAMESITE = None

SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False


# --------------------------------------------------
# CLAVE PRIMARIA POR DEFECTO
# --------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# --------------------------------------------------
# MEDIA FILES (Subida de imágenes)
# --------------------------------------------------

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
