# Generated by Django 5.0.7 on 2026-02-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incident",
            name="priority",
        ),
        migrations.AddField(
            model_name="incident",
            name="category",
            field=models.CharField(
                choices=[
                    ("ELECTRICITY", "Electricidad"),
                    ("PLUMBING", "Fontanería"),
                    ("SECURITY", "Seguridad"),
                    ("GARDENING", "Jardinería"),
                    ("CLEANING", "Limpieza"),
                    ("INFRASTRUCTURE", "Infraestructura"),
                    ("EMERGENCY", "Emergencia"),
                ],
                default="INFRASTRUCTURE",
                max_length=20,
                verbose_name="Categoría",
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="location",
            field=models.CharField(
                default="Ubicación no especificada",
                help_text="Ej: Bloque A, Piscina principal, Garaje nivel -2",
                max_length=150,
                verbose_name="Ubicación",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="incident",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de resolución"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="urgency",
            field=models.CharField(
                choices=[
                    ("NORMAL", "Normal"),
                    ("HIGH", "Alta"),
                    ("CRITICAL", "Crítica"),
                ],
                default="NORMAL",
                max_length=10,
                verbose_name="Nivel de urgencia",
            ),
        ),
    ]
