# Generated by Django 5.0.7 on 2026-02-18 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0002_remove_incident_priority_incident_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="incidents/"),
        ),
        migrations.AlterField(
            model_name="incident",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidents_assigned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="category",
            field=models.CharField(
                choices=[
                    ("ELECTRICITY", "Electricidad"),
                    ("PLUMBING", "Fontanería"),
                    ("SECURITY", "Seguridad"),
                    ("GARDENING", "Jardinería"),
                    ("CLEANING", "Limpieza"),
                    ("INFRASTRUCTURE", "Infraestructura"),
                    ("EMERGENCY", "Emergencia"),
                ],
                default="INFRASTRUCTURE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incidents_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="incident",
            name="location",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="incident",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Abierta"),
                    ("IN_PROGRESS", "En proceso"),
                    ("RESOLVED", "Resuelta"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="incident",
            name="urgency",
            field=models.CharField(
                choices=[
                    ("NORMAL", "Normal"),
                    ("HIGH", "Alta"),
                    ("CRITICAL", "Crítica"),
                ],
                default="NORMAL",
                max_length=10,
            ),
        ),
    ]
